vile:
  ignore:
    - ".*"
    - bin
    - coverage
    - doc
    - "*.json"
    - lib
    - LICENSE
    - "*.lock"
    - "*.log"
    - "*.md"
    - node_modules
    - src/@types
    - tags
    - test/fixtures
    - test/mocha.opts
    - tmp
    - vendor
    - "*.yml"

retire:
  config:
    node: true
    package: true
    js: false
    ignore:
      - .docs
depcheck:
  config:
    ignore_dev_deps: true
    ignore_dirs:
      - src
      - node_modules
      - coverage
      - "vile-**"
